version: "3.1"

services:
  mongodb:
    image: mongo
    container_name: my-mongodb-container
    # restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - my-network

  express-server:
    image: 767277b1d5c5
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: my-express-container
    # restart: always
    ports:
      - "3300:3300"
    networks:
      - my-network
    depends_on:
      - mongodb

volumes:
  mongodb_data:

networks:
  my-network:
